// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alexpts/edu-go/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ICategoryRepoMock is an autogenerated mock type for the ICategoryRepo type
type ICategoryRepoMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *ICategoryRepoMock) Create(ctx context.Context, _a1 *model.Category) (*model.Category, int64, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *model.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Category) (*model.Category, int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Category) *model.Category); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Category) int64); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.Category) error); ok {
		r2 = rf(ctx, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAll provides a mock function with given fields: ctx, relations
func (_m *ICategoryRepoMock) FindAll(ctx context.Context, relations ...string) ([]model.Category, error) {
	_va := make([]interface{}, len(relations))
	for _i := range relations {
		_va[_i] = relations[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []model.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) ([]model.Category, error)); ok {
		return rf(ctx, relations...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...string) []model.Category); ok {
		r0 = rf(ctx, relations...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, relations...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneById provides a mock function with given fields: ctx, uuid, relations
func (_m *ICategoryRepoMock) FindOneById(ctx context.Context, uuid string, relations ...string) (*model.Category, error) {
	_va := make([]interface{}, len(relations))
	for _i := range relations {
		_va[_i] = relations[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, uuid)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *model.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) (*model.Category, error)); ok {
		return rf(ctx, uuid, relations...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) *model.Category); ok {
		r0 = rf(ctx, uuid, relations...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, uuid, relations...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Persist provides a mock function with given fields: ctx, _a1
func (_m *ICategoryRepoMock) Persist(ctx context.Context, _a1 *model.Category) (*model.Category, int64, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *model.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Category) (*model.Category, int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Category) *model.Category); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Category) int64); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.Category) error); ok {
		r2 = rf(ctx, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *ICategoryRepoMock) Update(ctx context.Context, _a1 *model.Category) (*model.Category, int64, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *model.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Category) (*model.Category, int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Category) *model.Category); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Category) int64); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.Category) error); ok {
		r2 = rf(ctx, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewICategoryRepoMock creates a new instance of ICategoryRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICategoryRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICategoryRepoMock {
	mock := &ICategoryRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
