// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

func InjectA() (A, func(), error) {
	a, cleanup := provideA()
	return a, func() {
		cleanup()
	}, nil
}

// wire.go:

type A struct {
	Name string
}

func provideA() (A, func()) {
	return A{"Alex"}, func() {}
}
